readme upd + gitignore
VK-BMSTU-QA/homework-1 pull request #1
Opened 2022-02-13 15:06 UTC by renataclover

2022-02-13 15:11 UTC, VictoriaOtm commented on README.md
> +2. Создать таск в Jira типа "Задача" и назвать его "Тестирование <название команды>". При создании таска указать ему метку (поле "label") с названием вашей команды
вроде бы мы делали метку - название команды, а в названии задачи писали название проекта ребят, или я путаю?

2022-02-13 15:13 UTC, renataclover commented on README.md
> +2. Создать таск в Jira типа "Задача" и назвать его "Тестирование <название команды>". При создании таска указать ему метку (поле "label") с названием вашей команды
вообще, да. Ты права. На лекции @Betchika99 просто им сказала писать в таске "Тестирование <название команды>"

Я тогда не заметила. И вот думаю оставить или нет

2022-02-13 15:33 UTC, VictoriaOtm commented on README.md
> +2. Создать таск в Jira типа "Задача" и назвать его "Тестирование <название команды>". При создании таска указать ему метку (поле "label") с названием вашей команды
кажется лучше исправить, если у них будут вопросы, мы ответим, все равно они ориентируются на письменную доку в первую очередь. а если не поправим сейчас, то будем потом страдать))

2022-02-13 16:48 UTC, renataclover commented on README.md
> +2. Создать таск в Jira типа "Задача" и назвать его "Тестирование <название команды>". При создании таска указать ему метку (поле "label") с названием вашей команды
попраивла

2022-02-13 17:28 UTC, VictoriaOtm approved these changes

2022-02-13 17:45 UTC, Betchika99 requested changes

2022-02-13 17:45 UTC, Betchika99 commented on README.md
> +4. В github форкнуть этот репозиторий, после создать новую ветку с названием команды и добавить `markdown` файл с названием: `<название команды>-<год>.md`.
мб дать пример названия? а то не поймут, что за год

2022-02-13 17:45 UTC, Betchika99 commented on README.md
> +2. Создать таск в Jira типа "Задача" и назвать его "Тестирование <название **проекта**>". При создании таска указать ему метку (поле "label") с названием вашей команды
нужен линк на таск, который я на лекции делала?

2022-02-13 17:45 UTC, Betchika99 commented on README.md
> +### Как сдавать на проверку
мб этот пункт перенести повыше? до требований к отчёту, чтобы все действия были в одном месте

2022-02-13 17:45 UTC, Betchika99 commented on README.md
> +4. Скинуть своему ментору на ревью ссылку с таском. // todo: разбивка по менторам
может здесь добавить пункт вида "заасайнить своего ментора (если он у вас есть)"

2022-02-13 17:45 UTC, Betchika99 commented on README.md
> +## Сроки и баллы
будем здесь что-то писать про исправление замечаний от преподов? что есть время только в день рк

2022-02-13 17:50 UTC, renataclover commented on README.md
> +4. В github форкнуть этот репозиторий, после создать новую ветку с названием команды и добавить `markdown` файл с названием: `<название команды>-<год>.md`.
Спасибо, когда редактировала, не обратила внимание. Я бы вообще от года избавилась
@artemmur @Betchika99 что думаете?

2022-02-13 17:50 UTC, renataclover commented on README.md
> +2. Создать таск в Jira типа "Задача" и назвать его "Тестирование <название **проекта**>". При создании таска указать ему метку (поле "label") с названием вашей команды
можем добавить, скинь плиз

2022-02-13 17:52 UTC, renataclover commented on README.md
> +### Как сдавать на проверку
Я по структуре как раз именно так хотела
1) Всё что связано с подготовкой
2) Всё что связано с выполнением
3) Всё что связано отправкой на ревью

мне не оч нравится, когда требования находятся в самом конце

2022-02-13 17:53 UTC, renataclover commented on README.md
> +4. Скинуть своему ментору на ревью ссылку с таском. // todo: разбивка по менторам
я тут отметила `// todo` (писала об этом в телеге)
у нас нет разбиения чтобы на кого-то ассайнить пока или кидать

А так, да

2022-02-13 17:54 UTC, renataclover commented on README.md
> +## Сроки и баллы
Я думаю нет, т.к. препод сам выдаст замечания и срок. Им сначала надо получить аппрув от ментора 
Мне кажется, это дает больше гибкости нам, если мы идем кому-то на встречу и даем больше времени на правки

2022-02-13 18:10 UTC, renataclover commented on README.md
> +4. В github форкнуть этот репозиторий, после создать новую ветку с названием команды и добавить `markdown` файл с названием: `<название команды>-<год>.md`.
порешали, год будет в репе

2022-02-13 19:40 UTC, Betchika99 commented on README.md
> +2. Создать таск в Jira типа "Задача" и назвать его "Тестирование <название **проекта**>". При создании таска указать ему метку (поле "label") с названием вашей команды
https://jira.vk.team/browse/VKEDU-2

2022-02-14 22:25 UTC, Betchika99 approved these changes

2022-02-15 14:44 UTC, merged