VVT-i3.0
VK-BMSTU-QA/homework-1 pull request #21
Opened 2022-10-10 10:27 UTC by Natali-Skv

2022-10-10 14:51 UTC, kirill555101 approved these changes

2022-10-10 18:12 UTC, Andrey123815 approved these changes

2022-10-12 13:40 UTC, Natali-Skv commented
approved

2022-10-14 10:19 UTC, yutfut commented
approved

2022-10-14 10:19 UTC, yutfut commented
approved

2022-10-16 11:12 UTC, alexey-ershkov requested changes
Привет) отчет круто оформлен, лайк) Но в формулировках довольно часто встречается "корректно", "правильно" и "верно" - это общие слова, нужно в каждом из пунктов раскрывать что под этим вы имеете ввиду

Представьте, что этот отчет попадет тестировщику, который не знаком с вашим проектом

2022-10-16 11:12 UTC, alexey-ershkov commented on VVT-i 3.0.md
> +### "Доствка":
Доставка

2022-10-16 11:12 UTC, alexey-ershkov commented on VVT-i 3.0.md
> +# [Наш проект (Delivery-club)](https://tavide.xyz/main)
Не увидел тестов на навигацию, а это тоже является важным функционалом на сайтах

2022-10-16 11:12 UTC, alexey-ershkov commented on VVT-i 3.0.md
> +> :green_square: телефон пользователя отображается корректно, указан верно
Что такое корректно - нужно раскрыть, здесь и далее

2022-10-16 11:12 UTC, alexey-ershkov commented on VVT-i 3.0.md
> +>:green_square: название ресторана отображается корректно и указано верно
Что значит верно?

2022-10-16 11:12 UTC, alexey-ershkov commented on VVT-i 3.0.md
> +>:green_square: дополнительная информация о блюде (масса, ккал) отображается корректно, указана правильно
Что значит правильно?

2022-10-17 20:48 UTC, Natali-Skv commented on VVT-i 3.0.md
> +# [Наш проект (Delivery-club)](https://tavide.xyz/main)
добавили блок тестов на навигацию:
- тест  поведения при нажатии :arrow_left:  :arrow_right: навигационных кнопок браузера.
- тест поведения при вбивании в адресную строку  "https://tavide.xyz/ordering" (адреса тестируемой страницы)

2022-10-17 21:03 UTC, Natali-Skv commented on VVT-i 3.0.md
> +> :green_square: телефон пользователя отображается корректно, указан верно
все "корректно","правильно","верно" постарались конкретизировать.

2022-10-18 17:26 UTC, alexey-ershkov requested changes
Конкретизируйте что хотите проверить на "корректно с точки зрения верстки" и что хотите проверить на "ascii и русские символы отображаются корректно", нужны измеримые критерии того, как проверять, с чем сравнивать

2022-10-18 17:26 UTC, alexey-ershkov commented on VVT-i 3.0.md
> +>:green_square: символы ascii и русского алфавита отображаются корректно
Вот тут все еще осталось корректно - тут непонятно что проверять. Например в инпут можно ввести только символы ascii и русского алфавита или еще что. Постарайтесь конкретизировать такие проверки

2022-10-18 17:26 UTC, alexey-ershkov commented on VVT-i 3.0.md
> +>:green_square: картинка отображается корректно с точки зрения верстки
Что такое корректно с точки зрения верстки? 
Например:
- Отображается в соотвествии с макетом 
- Картинка показывается на экране
- В соотвествии со скрином
- К ней применяются определенные классы

2022-10-20 17:40 UTC, closed without merging