Lost pointer
VK-BMSTU-QA/homework-1 pull request #3
Opened 2022-03-10 16:26 UTC by frbgd

2022-03-19 15:48 UTC, alexey-ershkov requested changes
Привет, посмотрел работу, есть три главные проблемы, которые нужно поправить
1) Нет единого стиля оформления отчет и не понятна его структура. Привести к единой, можно добавить содержание и пр. 

2) Мало положительных кейсов

3) В случае кейсов с багами у вас описаны только баги. Нужно чтобы были и тест кейсы

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +**Регистрация и авторизация**
В маркадуне есть заголовки, который делаются с помощью # - [посмотрите здесь](https://www.markdownguide.org/basic-syntax/). Кажется заголовки будут уместнее, чем жирный текст

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +    ФР: поля ввода смещаются влево, ошибки смещены относительно полей ввода
**ФР** и **ОР** - непонятные сокращения, либо добавить до тест кейсов примечания с пояснениями сокращений, либо пишите полностью

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +
Нет описания тестового окружения

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +1. ❌При вводе неверных данных во время регистрации
Если это баг - выделите его отдельно, сначала опишите кейс, после баг

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +    ОР: поля ввода остаются на месте, ошибки находятся рядом с полями ввода
В регистрации мало положительных кейсов

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +        почта: [djewui@gmail.com](mailto:djewui@gmail.com)
почта в гитхабе не отображется как задумано, посмотрите и мб лучше без ссылки

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +2. ❌При вводе email с символом “_”
Крестик и галочки не оч понятные обозначения - их тоже есть смысл вынести в примечания и объяснить

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +   И нажатии на кнопку регистрации пользователь попадает на главную страницу сайта, в углу появляется стандартная аватарка
Что такое стандартная аватарка?

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +   Пользователь попадает на главную страницу сайта, в углу появляется установленная пользователем аватарка
Почему такое поведение, какая аватарка установлена пользователем?

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +1. ❌При попытке воспроизведения альбома с главной страницы незалогиненного пользователя перекидывает на страницу входа. После входа:
что есть попытка? Кажется можно просто написать, что _при вопспроизведении_

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +6. ✅При нажатии на кнопку воспроизведения в списке “Suggested Tracks” начинает воспроизводиться выбранный трек, кнопка “Воспроизвести” меняется на кнопку “Приостановить”, при нажатии на кнопку “Приос
Несколько кейсов в одном

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +8. ✅При нажатии на “Public Playlists” загружается список публичных плейлистов. При повторном нажатии не происходит повторной подгрузки данных с сервера
Два кейса в одном

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +Результат аналогичен при нахождении пользователя на странице избранного и повторном нажатии на иконку “Избранное”
Аналогичен чему? Лучше писать конкретно и сухо, не отсылаясь к другим пунктам и тд (см. описание частых ошибок домашки)

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +11. ✅При нажатии на иконку сердца в левой панели сайта происходит переход на страницу /favorites
что за страница /favorites?  Как понять что это она?

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +3. ❌При вводе пароля с символами кириллицы (напр. РАШГ743ар)
Добавить пробелы после крестиков и галочек, а то очень трудно читать

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +16. ⚠️При нажатии на аватарку пользователь попадает в настройки профиля - дублирование функциональности
что обозначает значок перед описанием?

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +**Страница альбома**
Мало позитивных кейсов

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +1. ❌При наличии одного трека в альбоме (сингл) отступы у кнопок в списке “Tracks”
Опять же  - все что у вас обозначено как баг, сначала должно быть описано, как тест кейс, а после уже сам баг, ибо у вас расходятся формулировки, когда все в порядке и когда нет, а должны быть одинаковые. Тестовый отчет должен быть в едином стиле, как и тест кейсы

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +Изменение названия
Почему новая нумерация? до этого же нумеровали кейсы по страницам

Изменение названия чего?

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +Шэринг плейлистов (публичность)
Шеринг - сленг, его быть не должно. Посмотрите по проекту  в целом наличие сленга и уберите его

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +3. ✅при загрузке прямоугольного изображения обложка не сужается/не расширяется, а центрируется
То с заглавной, то со строчной буквы. В целом ваш тестовый отчет оформлен в разной стилистике и не использует все плюшки маркдауна. Приведите все к единому стилю. Названия кнопок на сайте выделите и добавьте к ним их фото, чтобы было понятно на что нажимать. 

Держите в голове, что незнакомый с вашим проектом ручной тестировщик по вашем тестовому отчету должен провести полный регресс. Если вы сами понимаете, когда читаете пункт, что непонятно куда тыкать, какой результат и пр и нужно знать проект, чтобы это понять - то добавьте тогда больше описания, скрины куда нужно нажимать, какие кнопки и прочее. Это важно, так как вы сэкономите время тестировщика и избавите его от размышления о неоднозначностях результата

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +**Страница исполнителя**
Мало положительных кейсов

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +8. до и после воспроизведения видео на странице исполнителя фоновая обложка артиста находится в разных положениях
В целом забили на собственные правила стилизации, теперь нет никаких знаков. Отсылаю к комментарию выше привести все к единому стилю и использовать мощь Markdown

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +**Профиль пользователя**
Тоже мало положительных кейсов

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +* Работа на нескольких вкладках
Что это за список, зачем он, какую смысловую нагрузку несет?

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +* Перемотка
Перемотка чего?

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +9. ✅Регулировка громкости работает как ожидается, иконка динамика позволяет полностью отключить звук или восстановить уровень звука, заданный регулятором громкости
Несколько кейсов в одном

2022-03-19 15:48 UTC, alexey-ershkov commented on LostPointer.md
> +ссылки
Это можно вынести в отдельный пункт - навигация

2022-03-24 07:00 UTC, frbgd commented
Апрув

2022-03-24 09:58 UTC, 23-yo-designer-from-san-francisco commented
Апрув

2022-03-24 15:40 UTC, VictoriaOtm commented on LostPointer.md
> +# Главная страница
разбить главную на подразделы

2022-03-25 11:17 UTC, VictoriaOtm commented
апрув

2022-03-25 11:17 UTC, closed without merging