Yo ДЗ1.1
VK-BMSTU-QA/homework-1 pull request #4
Opened 2022-03-14 13:59 UTC by zdesbilaksenia

2022-03-14 21:54 UTC, mistergahan requested changes

2022-03-14 21:54 UTC, mistergahan commented on Yo.md
> +	1. Для создания мероприятия поле должно быть обязательно заполнено.
можем ли создать мероприятие с прошедшей датой?

2022-03-14 21:54 UTC, mistergahan commented on Yo.md
> +	1. У тега есть максимальная допустимая длина - 30 символов. Поле запрещает ввод символов при достижении лимита.
" " может быть тегом?

2022-03-19 16:44 UTC, zdesbilaksenia commented on Yo.md
> +	1. У тега есть максимальная допустимая длина - 30 символов. Поле запрещает ввод символов при достижении лимита.
строка 212 - ответ

2022-03-19 16:44 UTC, zdesbilaksenia commented on Yo.md
> +
обязательно добавим, когда джира перестанет нас отторгать хы

2022-03-20 09:45 UTC, a-shirshov commented on Yo.md
> +(Поле Фамилия требует только буквы).
Я попробовал, но становится тяжело читать, ибо приходится, искать часто описание поля, чтобы смотреть, что утчено.

2022-03-20 17:01 UTC, zdesbilaksenia commented on Yo.md
> +	1. Открывает файловый менеджер для выбора изображения на аватар.
если честно, мы не нашли, как это проверить....

2022-03-20 17:22 UTC, just4n4cc commented on Yo.md
> +- Кнопка “Войти”:
![image](https://user-images.githubusercontent.com/71648520/159174556-da457f0e-67c0-46fb-ac96-e3dd276ef3a2.png)
![image](https://user-images.githubusercontent.com/71648520/159174562-47e1617b-1d37-4634-a0bd-0df9d9b63138.png)
нет, они разные

2022-03-20 20:51 UTC, mistergahan approved these changes
Ждем доступов на джиру и с ними уже добавляем сюда ссылки

2022-03-24 15:52 UTC, just4n4cc approved these changes

2022-04-01 16:29 UTC, closed without merging