GoToV
VK-BMSTU-QA/homework-1 pull request #6
Opened 2022-03-20 18:12 UTC by Flash1ee

2022-03-21 20:51 UTC, alexey-ershkov requested changes
Привет) Отписал основные моменты, они в целом по всей работе встречаются. Из-за большого количества похожих скринов сложно читать отчет, мог увидеть не все. 

Главные моменты:
- Проверка != баг, их описания различаются
- Не нужно делать кучу похожих скриншотов экрана в проверку, а добавлять только нужную часть экрана. И не дублировать изображения
- Тесты на навигацию в отдельный блок

Лайк за содержание и ссылки)

2022-03-21 20:51 UTC, alexey-ershkov commented on gotov.md
> +Браузер + версия: `Google Chrome Версия 96.0.4664.55 (Официальная сборка),(x86_64)`.
В случае мака можно указать и процессор (arm или intel)

2022-03-21 20:51 UTC, alexey-ershkov commented on gotov.md
> +**Контекст** - авторизированный пользователь, у которого нет ни одной подписки
Баги описаны хорошо, но нужно оформить это немного иначе - смотрите условие задания. Баги и тест кейсы должны различаться

У вас должен получиться список проверок, а если в вашем проекте это проверка не проходит, то тогда уже описывать баг, как у вас сделано. 

То есть не должно быть **фактический результат**: ОК

2022-03-21 20:51 UTC, alexey-ershkov commented on gotov.md
> +
Скриншоты не информативны - не понятна про какую кнопку идет речь. Лучше делать точечные скриншоты, а не всей страницы

2022-03-21 20:51 UTC, alexey-ershkov commented on gotov.md
> +<img width="781" alt="Снимок экрана 2022-03-20 в 12 13 02" src="https://user-images.githubusercontent.com/55987935/159155738-91e60239-6fde-4376-a830-17df3f9a9747.png">
Не нужно вставлять одну и ту же картинку несколько раз. Опишите все тесткейсы для картинки и потом просто сошлитесь на нее

2022-03-21 20:51 UTC, alexey-ershkov commented on gotov.md
> +***Ожидаемый результат*** - пуши о новых постах не приходят.
То есть формат описания будет вида:

_У авторизованного пользователя пуши о новых постах не приходят_

Далее отдельно описываете баг

2022-03-21 20:51 UTC, alexey-ershkov commented on gotov.md
> +# Домашнее задание 1
Не увидел тестирования навигации по сайту, если оно размазано по страницам, то лучше выделить в отдельный блок

2022-03-24 07:36 UTC, imkamie commented
Аппрув

2022-03-24 11:26 UTC, Flash1ee commented
Approved

2022-03-24 12:58 UTC, VolodyaLarin commented
Approved

2022-03-24 13:47 UTC, alexey-ershkov commented
Аппрув от ментора

2022-03-24 14:45 UTC, ThCompiler commented
Аппрув

2022-03-24 21:09 UTC, closed without merging